[package]
name = "druid-template"
version = "0.1.0"
authors = ["Perhaps A. Human <hi@example.com>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/xi-editor/druid.git", rev = "c4f92c10", version = "0.6" }
